version: '3.7'

services:
  db:
    image: postgres:16
    container_name: observador-back
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=observadordb
    volumes:
      - ./postgres:/var/lib/postgresql/data